# Generated by Django 4.2 on 2025-02-21 02:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_auto_20250221_0220"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="avatar",
        ),
    ]
