# Generated by Django 4.2 on 2025-02-21 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("content_manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Kategori", "verbose_name_plural": "Kategoriler"},
        ),
        migrations.AddField(
            model_name="category",
            name="type",
            field=models.CharField(
                choices=[
                    ("blog", "Blog"),
                    ("category", "Kategori İçeriği"),
                    ("product", "Ürün İçeriği"),
                ],
                default="blog",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="content",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="content_manager.category",
            ),
        ),
        migrations.AlterField(
            model_name="content",
            name="seo_title",
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
