# Generated by Django 4.2 on 2025-03-04 05:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content_manager", "0002_alter_category_options_category_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="heading_structure",
            field=models.TextField(
                blank=True, help_text="JSON formatında başlık yapısı", null=True
            ),
        ),
    ]
