# Generated by Django 4.2 on 2025-02-21 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("content_manager", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SEOAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_score", models.IntegerField(default=0)),
                ("meta_description_score", models.IntegerField(default=0)),
                ("content_score", models.IntegerField(default=0)),
                ("keyword_density", models.FloatField(default=0.0)),
                ("readability_score", models.IntegerField(default=0)),
                ("overall_score", models.IntegerField(default=0)),
                ("analyzed_at", models.DateTimeField(auto_now=True)),
                (
                    "content",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content_manager.content",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "SEO Analyses",
            },
        ),
        migrations.CreateModel(
            name="KeywordAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keyword", models.CharField(max_length=100)),
                ("frequency", models.IntegerField(default=0)),
                ("density", models.FloatField(default=0.0)),
                ("competition_score", models.FloatField(default=0.0)),
                ("search_volume", models.IntegerField(default=0)),
                ("analyzed_at", models.DateTimeField(auto_now=True)),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content_manager.content",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Keyword Analyses",
            },
        ),
    ]
