# Generated by Django 4.2 on 2025-02-21 02:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("content_manager", "0002_alter_category_options_category_type_and_more"),
        ("seo_analyzer", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="keywordanalysis",
            options={
                "verbose_name": "Anahtar Kelime Analizi",
                "verbose_name_plural": "Anahtar Kelime Analizleri",
            },
        ),
        migrations.AlterModelOptions(
            name="seoanalysis",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "SEO Analizi",
                "verbose_name_plural": "SEO Analizleri",
            },
        ),
        migrations.RenameField(
            model_name="keywordanalysis",
            old_name="frequency",
            new_name="count",
        ),
        migrations.RenameField(
            model_name="seoanalysis",
            old_name="content_score",
            new_name="meta_description_length",
        ),
        migrations.RenameField(
            model_name="seoanalysis",
            old_name="meta_description_score",
            new_name="meta_title_length",
        ),
        migrations.RenameField(
            model_name="seoanalysis",
            old_name="overall_score",
            new_name="score",
        ),
        migrations.RenameField(
            model_name="seoanalysis",
            old_name="analyzed_at",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="seoanalysis",
            old_name="readability_score",
            new_name="word_count",
        ),
        migrations.RemoveField(
            model_name="keywordanalysis",
            name="analyzed_at",
        ),
        migrations.RemoveField(
            model_name="keywordanalysis",
            name="competition_score",
        ),
        migrations.RemoveField(
            model_name="keywordanalysis",
            name="content",
        ),
        migrations.RemoveField(
            model_name="keywordanalysis",
            name="search_volume",
        ),
        migrations.RemoveField(
            model_name="seoanalysis",
            name="keyword_density",
        ),
        migrations.RemoveField(
            model_name="seoanalysis",
            name="title_score",
        ),
        migrations.AddField(
            model_name="keywordanalysis",
            name="analysis",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="seo_analyzer.seoanalysis",
            ),
        ),
        migrations.AddField(
            model_name="keywordanalysis",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="seoanalysis",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="seoanalysis",
            name="content",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="content_manager.content",
            ),
        ),
    ]
