# Generated by Django 4.2 on 2025-02-21 03:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("seo_analyzer", "0002_alter_keywordanalysis_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="seoanalysis",
            old_name="meta_description_length",
            new_name="description_score",
        ),
        migrations.RenameField(
            model_name="seoanalysis",
            old_name="meta_title_length",
            new_name="keyword_score",
        ),
        migrations.RenameField(
            model_name="seoanalysis",
            old_name="score",
            new_name="overall_score",
        ),
        migrations.RenameField(
            model_name="seoanalysis",
            old_name="word_count",
            new_name="title_score",
        ),
        migrations.RemoveField(
            model_name="seoanalysis",
            name="updated_at",
        ),
    ]
