# Generated by Django 4.2 on 2025-02-21 02:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("content_manager", "0002_alter_category_options_category_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("total_views", models.IntegerField(default=0)),
                ("unique_visitors", models.IntegerField(default=0)),
                ("avg_session_duration", models.IntegerField(default=0)),
                ("bounce_rate", models.FloatField(default=0.0)),
            ],
            options={
                "verbose_name": "Günlük Analitik",
                "verbose_name_plural": "Günlük Analitikler",
                "ordering": ["-date"],
            },
        ),
        migrations.AlterModelOptions(
            name="contentanalytics",
            options={
                "verbose_name": "İçerik Analitiği",
                "verbose_name_plural": "İçerik Analitikleri",
            },
        ),
        migrations.RenameField(
            model_name="contentanalytics",
            old_name="last_updated",
            new_name="updated_at",
        ),
        migrations.RemoveField(
            model_name="contentanalytics",
            name="unique_visitors",
        ),
        migrations.RemoveField(
            model_name="contentanalytics",
            name="views",
        ),
        migrations.AddField(
            model_name="contentanalytics",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contentanalytics",
            name="view_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="contentanalytics",
            name="avg_time_spent",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("view", "Görüntüleme"),
                            ("create", "Oluşturma"),
                            ("edit", "Düzenleme"),
                            ("delete", "Silme"),
                        ],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content_manager.content",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Kullanıcı Aktivitesi",
                "verbose_name_plural": "Kullanıcı Aktiviteleri",
                "ordering": ["-created_at"],
            },
        ),
    ]
